# Input Settings: initialize base input folder names,
# dataset collections, and algorithms to run over
input_settings:

    # Base input directory
    input_dir : "inputs"

    # Subdirectory of inputs that datasets are placed in
    dataset_dir: "Synthetic/dyn-LI"

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   exprData: scRNA-Seqexpression file name
    #   cellData: a file containing pseudotime ordering
    #   trueEdges: a file contaning reference network for evaulation
    datasets:
        - name: "dyn-LI-100-1"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          
        - name: "dyn-LI-100-2"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          
        - name: "dyn-LI-100-3"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          
        - name: "dyn-LI-100-4"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          
        - name: "dyn-LI-100-5"
          exprData: "ExpressionData.csv"
          cellData: "PseudoTime.csv"
          trueEdges: "refNetwork.csv"
          

    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    # Denotes a list of algorithms to run. Each has the following parameters:
    #   name: Name of the algorithm. Must be recognized by the pipeline, see
    #       code for acceptable values
    #
    #   should_run: whether or not to run the algorithm
    #
    #   params: any additional, algorithm-specific parameters
    #       should be specified in the params map for a given algorithm
    #
    algorithms:                        
              
        - name: "PIDC"
          params: 
              should_run: [True]
              
              
              
        - name: "GRNBOOST2"
          params: 
              should_run: [True]                
              
              
        - name: "SCODE"
          params:
              should_run: [True]
              z: [4]
              nIter: [100]
              nRep: [5]


        - name: "SINCERITIES"
          params: 
              should_run: [True]
              nBins: [15]



# Output Settings: initialize base output folder names
output_settings:

    # Base output directory
    output_dir: "outputs"
    output_prefix: "dyn-LI"
